// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAayc6Dh4VrFHdIMDdp_IZ5YNYJ1C7GcY',
    appId: '1:748579978540:web:d8612d6afc28df52e2c089',
    messagingSenderId: '748579978540',
    projectId: 'wegowolf-b87a6',
    authDomain: 'wegowolf-b87a6.firebaseapp.com',
    storageBucket: 'wegowolf-b87a6.firebasestorage.app',
    measurementId: 'G-267K44GXLG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBexmc7GN8QV3Q2sAcN6R8U70E6gJnxRPM',
    appId: '1:748579978540:android:28910cc983973f82e2c089',
    messagingSenderId: '748579978540',
    projectId: 'wegowolf-b87a6',
    storageBucket: 'wegowolf-b87a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZR8PE-vrnomVAb87Wf9ERhUYWg_5n9KU',
    appId: '1:748579978540:ios:7eb0a189eb22e4a1e2c089',
    messagingSenderId: '748579978540',
    projectId: 'wegowolf-b87a6',
    storageBucket: 'wegowolf-b87a6.firebasestorage.app',
    iosBundleId: 'com.wegowolf.wegowolf',
  );
}
